apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: moderation
  template:
    metadata:
      labels:
        apps: moderation
    spec:
      containers:
        - name: moderation
          image: usmanubaid98/moderation:latest

---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  type: ClusterIP
  selector:
    apps: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
