apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: posts
  template:
    metadata:
      labels:
        apps: posts
    spec:
      containers:
        - name: posts
          image: usmanubaid98/posts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  type: ClusterIP
  selector:
    apps: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
