apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: query
  template:
    metadata:
      labels:
        apps: query
    spec:
      containers:
        - name: query
          image: usmanubaid98/query:latest

---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: ClusterIP
  selector:
    apps: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
